# Generated by Django 5.0.4 on 2024-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_customuser_notification_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notification_setting',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_settings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
