# Generated by Django 5.0.4 on 2024-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_customuser_notification_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notification_settings',
            field=models.JSONField(default=list),
        ),
    ]
